// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKy2g_AjJC5NUi9fijjixtHvG7zUIgZXw',
    appId: '1:85861487728:web:cdb65351d072dd9f8b50b5',
    messagingSenderId: '85861487728',
    projectId: 'money-fb132',
    authDomain: 'money-fb132.firebaseapp.com',
    storageBucket: 'money-fb132.appspot.com',
    measurementId: 'G-BYPSLLEGC1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1e0n_wD2C8B5HYvoP8g8NaJxX5oSpHoM',
    appId: '1:85861487728:android:14df0ec7d32d9a848b50b5',
    messagingSenderId: '85861487728',
    projectId: 'money-fb132',
    storageBucket: 'money-fb132.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTNHD1-nqmjoYCcKL4HtBj0_awk8LY_T0',
    appId: '1:85861487728:ios:9694788bbcaa6e118b50b5',
    messagingSenderId: '85861487728',
    projectId: 'money-fb132',
    storageBucket: 'money-fb132.appspot.com',
    androidClientId: '85861487728-a8n2328epcaga3ehrgui3o85vdbamerq.apps.googleusercontent.com',
    iosClientId: '85861487728-kkkfetavkbmau3ehks646e9fbrjmb0r9.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTNHD1-nqmjoYCcKL4HtBj0_awk8LY_T0',
    appId: '1:85861487728:ios:6866c5763ea5d0508b50b5',
    messagingSenderId: '85861487728',
    projectId: 'money-fb132',
    storageBucket: 'money-fb132.appspot.com',
    androidClientId: '85861487728-a8n2328epcaga3ehrgui3o85vdbamerq.apps.googleusercontent.com',
    iosClientId: '85861487728-cp0edt54db6arkp69clfmlrheafp8804.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTracker.RunnerTests',
  );
}
